### ISSUE TITLE
Issue with branch names when using git tag

### ISSUE THREAD

**Issue by kushtrimjunuzi** [appleboy/drone-sftp-cache#10]
The issue is that this plugin creates a hash file name based on branch name and mount path and every time you git tag you will have new cache file. DRONE_BRANCH and DRONE_TAG are the same at least for bitbucket.org. I saw the commented code that handles fallback when there is no cache file it takes from master by default and that is as a DRONE_REPO_BRANCH.
So my question is can we handle this situation by using DRONE_REPO_BRANCH value as fallback?

**Comment by dvmorris** [comment]
@kushtrimjunuzi we are running into the same issue. Did you have any luck making a change to fix this?

**Comment by kushtrimjunuzi** [comment]
@dvmorris merge with my pull request, I know there are few other nice changes and also this one is at the last commit, take a look at this one https://github.com/drone-plugins/drone-sftp-cache/pull/6/commits/40283f561c4ff2133e904e56af6bab5745ce1cee

**Comment by appleboy** [comment]
@kushtrimjunuzi I add `IgnoreBranch` flag for ignoring branch name.

Try the following config.

```yml
  # restore the cache from an sftp server
  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ cache, node_modules, .yarn-cache ]
    ignore_branch: true
```

see https://github.com/appleboy/drone-sftp-cache/commit/04a39b7e38547331ff0a9f3e152c2e0e8612524e
