### ISSUE TITLE
SFTP does not work when using secrets

### ISSUE THREAD

**Issue by dcerecedo** [appleboy/drone-sftp-cache#14]
I have configured the Drone yml file with all credentials stored in it and works:

```
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount: [repository]
    server: subdom.server.com:22
    path: /home/deployment/cache/repository
    username: someone
    password: secret
```

I then add secrets to the repo:

```
drone secret add --image=plugins/sftp_cache owner/repo username someone
drone secret add --image=plugins/sftp_cache owner/repo password secret
drone secret add --image=plugins/sftp_cache owner/repo server subdom.server.com:22
```

Check that secrets are stored:

```
drone secret ls owner/repo

SFTP_CACHE_USERNAME 
Images: plugins/sftp_cache
Events: push, tag, deployment

SFTP_CACHE_PASSWORD 
Images: plugins/sftp_cache
Events: push, tag, deployment

SFTP_CACHE_SERVER 
Images: plugins/sftp_cache
Events: push, tag, deployment
```

Sign the yml:

`drone sign`

And push the changes to bitbucket getting the following error when building:

![image](https://cloud.githubusercontent.com/assets/4864470/18439353/3ee02406-7905-11e6-8d7e-a113d037066e.png)
